### ISSUE TITLE
Tile areas

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#169]
### Enter your feature description.

You can define tile areas - specified tiles then only spawn and are randomized within these areas/coordinates

<details><summary>Maybe something like:</summary>

```
tile_area "xyz"
{
    area_coord
    {
        x
        y
    }

        tile a
        tile b
        tile c
}
```
</details>

color only to illustrate
![tile_regions_03](https://user-images.githubusercontent.com/97815025/185681070-3c2ea4c4-adbb-404b-8b14-31f23913ec4d.png)

**Comment by lukaasm** [comment]
This is implemented in some way already but in the `.mission` file which drives MapGenerator

![image](https://user-images.githubusercontent.com/48881/185695891-269a37dc-4dbe-4251-a2c1-90b54c6e0c1d.png)

To have a nice visual editor for that I would need to think about how to integrate that into LevelEditor in a non-confusing way since LevelEditor mostly deals with 'tiles' which are the lowest building blocks for MapGenerator and tiles can be referenced by many mission files

**Comment by Molch1** [comment]
Perfect, thank you so much for everything!
