### ISSUE TITLE
Allow opening/closing folders with a direct click

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#346]
### Enter your feature description.

Would be handy if we could simply open/close workspace folders with a direct click on them
![grafik](https://user-images.githubusercontent.com/50502395/224494228-13b4080a-7e93-4212-847f-27578670d263.png)

Like that you don't have to aim for the little arrow all the time

**Comment by lukaasm** [comment]
Maybe it should be "configurable", I had complaints that on windows/other explorer like tools by default single click is selection and expansion is made by clicking on the arrow / double click ( I need to implement that ) :P

And since widget is shared in a lot of places, behaviour should be consistent :p
